# Generated by Django 5.0.3 on 2024-03-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('nature', models.CharField(choices=[('entry', 'Entrada'), ('output', 'Saida')], max_length=8)),
                ('type_cash', models.CharField(choices=[('cc', 'Cartão de Crédito'), ('cd', 'Cartão de Débito'), ('din', 'Dinheiro'), ('pix', 'Pix')], max_length=8)),
                ('value', models.CharField(max_length=10)),
            ],
        ),
    ]
