# Generated by Django 5.0.3 on 2024-03-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0003_alter_registermodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='type_cash',
            field=models.CharField(blank=True, choices=[('cc', 'Cartão de Crédito'), ('cd', 'Cartão de Débito'), ('din', 'Dinheiro'), ('pix', 'Pix')], max_length=8),
        ),
    ]
