# Generated by Django 5.0.3 on 2024-03-26 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0005_registermodel_created_at_registermodel_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registermodel',
            options={'verbose_name': 'Registro de caixa', 'verbose_name_plural': 'Registros'},
        ),
    ]
