# Generated by Django 5.0.3 on 2024-03-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0006_alter_registermodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='nature',
            field=models.CharField(choices=[('entry', 'Entrada'), ('output', 'Saida')], default='Entrada', max_length=8),
        ),
    ]
